### ISSUE TITLE
How to use in Windows 10

### ISSUE THREAD

**Issue by Beneun** [monsta-hd/scripts#1]
Would be really useful for me.

Could you explain how to use with Windows 10?

**Comment by yell** [comment]
Hi, to which scripts are you referring to? Or to all of them?

In general, you have to make sure python 2.7 is installed, and so are all dependencies listed in `requirements.txt` (either using `pip` just like in README or perhaps using Anaconda, which is considered a more reliable way of running python on windows).

Next, follow any additional steps if there are any and run the program as regular python scripts.

**Comment by Beneun** [comment]
Benedikt Neundoerfer
Am Weinbrunnen 3
66333 Völklingen
Germany

Hello again,

sorry to bother you again.

But as I do not belong to that seemingly blessed group of people whose 
natural environment seems to be - environments-, may I ask for further 
assistance on running your script?

As you recommanded, I installed anaconda on my Windows 10 PC.

Not sure what else to do, I simply installed chromedriver.exe, 
Evernote-Web-Clipper_v6.132.crx, config.yml and evernote_url2clip.py in 
the /User/.../Anaconada2 directory.

Unfortunately, I always get an "invalid syntax" error.

So what else would I have to do to get the script running?


Best regards,
Benedikt Neundoerfer





------ Originalnachricht ------
Von: "Yelysei Bondarenko" <notifications@github.com>
An: "monsta-hd/scripts" <scripts@noreply.github.com>
Cc: "Beneun" <benedikt.neundoerfer@gmx.net>; "Author" 
<author@noreply.github.com>
Gesendet: 11.01.2018 12:13:33
Betreff: Re: [monsta-hd/scripts] How to use in Windows 10 (#1)

**Comment by yell** [comment]
- I updated the script (as well as some fixes regarding `selenium` since by the time of rewriting the script it was updated from `3.7.0` to `3.9.0`) and also added precise instructions to README how to install and run on Windows environment. I tested on Windows 8.1, but I'm sure this should work on 10th too
- Always make sure that some strange errors might occur if the chrome driver is not of the latest version (i.e. before trying anything make sure you have the latest version of driver, and that it is added to PATH, which is `X:/Windows/System32` on Windows)

Please reopen the issue if you have further questions
